services:
  app:
    build: .
    container_name: auth_app
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      - postgres
      - redis
    restart: always

  postgres:
    image: postgres:18-alpine
    container_name: auth_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - "${DB_PORT}:5432"
    restart: always

  redis:
    image: redis:7-alpine
    container_name: auth_redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  db_data:
